# Generated by Django 6.1 on 2026-08-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=100, verbose_name='توكن بوت تيليجرام')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, verbose_name='Chat ID')),
                ('notify_low_balance', models.BooleanField(default=True, verbose_name='تنبيه عند اقتراب حد المديونية')),
                ('notify_new_debt', models.BooleanField(default=True, verbose_name='تنبيه عند تسجيل دين جديد')),
                ('notify_subscriber_expiry', models.BooleanField(default=False, verbose_name='تنبيه قبل انتهاء اشتراك عميل بيوم')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core.company')),
            ],
            options={
                'verbose_name': 'إعدادات التنبيهات',
                'verbose_name_plural': 'إعدادات التنبيهات',
            },
        ),
    ]
