# Generated by Django 6.1 on 2026-08-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم بالكامل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('username', models.CharField(max_length=64, verbose_name='اسم المستخدم')),
                ('password', models.CharField(max_length=64, verbose_name='كلمة المرور')),
                ('mac_lock', models.CharField(blank=True, help_text='اتركه فارغًا للسماح بالدخول من أي جهاز', max_length=17, verbose_name='قفل بجهاز معين (MAC)')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('expired', 'منتهي')], default='active', max_length=12, verbose_name='الحالة')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='core.company', verbose_name='الشركة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='plans.plan', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'مشترك',
                'verbose_name_plural': 'المشتركون',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'username'), name='uniq_username_per_company')],
            },
        ),
    ]
