# Generated by Django 6.1 on 2026-09-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriber',
            name='uniq_username_per_company',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='username',
            field=models.CharField(help_text='فريد على مستوى المنصة كلها (لأن العميل بيكتبه في صفحة الهوت سبوت مباشرة)', max_length=64, unique=True, verbose_name='اسم المستخدم'),
        ),
    ]
