# Generated by Django 6.1 on 2026-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_remove_subscriber_uniq_username_per_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد (من كروت الشحن)'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النقل لسلة المهملات'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='في سلة المهملات'),
        ),
    ]
