# Generated by Django 6.1 on 2026-09-02 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companysettings_subaccountinvite'),
        ('subscribers', '0003_subscriber_balance_subscriber_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='can_self_renew',
            field=models.BooleanField(default=True, verbose_name='يقدر يجدد اشتراكه بنفسه من البوابة'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='can_self_topup',
            field=models.BooleanField(default=True, verbose_name='يقدر يشحن رصيده بنفسه من البوابة'),
        ),
        migrations.CreateModel(
            name='SubscriberGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم المجموعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_groups', to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مجموعة مشتركين',
                'verbose_name_plural': 'مجموعات المشتركين',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='subscribers.subscribergroup', verbose_name='المجموعة'),
        ),
    ]
