# Generated by Django 6.1 on 2026-08-29 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NASServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: عمود شارع النصر', max_length=150, verbose_name='اسم الجهاز')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('secret', models.CharField(max_length=150, verbose_name='المفتاح السري (RADIUS Secret)')),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='المنطقة')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('is_online', models.BooleanField(default=False, verbose_name='متصل الآن')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nas_servers', to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'جهاز ميكروتيك',
                'verbose_name_plural': 'أجهزة الميكروتيك',
                'ordering': ['name'],
            },
        ),
    ]
