# Generated by Django 6.1 on 2026-08-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasserver',
            name='api_password',
            field=models.CharField(blank=True, max_length=150, verbose_name='باسورد RouterOS API'),
        ),
        migrations.AddField(
            model_name='nasserver',
            name='api_port',
            field=models.PositiveIntegerField(default=8728, verbose_name='بورت RouterOS API'),
        ),
        migrations.AddField(
            model_name='nasserver',
            name='api_username',
            field=models.CharField(blank=True, default='admin', max_length=100, verbose_name='يوزر RouterOS API'),
        ),
        migrations.AddField(
            model_name='nasserver',
            name='last_test_result',
            field=models.CharField(blank=True, max_length=255, verbose_name='نتيجة آخر اختبار اتصال'),
        ),
    ]
