# Generated by Django 6.1 on 2026-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas_manager', '0002_nasserver_api_password_nasserver_api_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasserver',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النقل لسلة المهملات'),
        ),
        migrations.AddField(
            model_name='nasserver',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='في سلة المهملات'),
        ),
        migrations.AddField(
            model_name='nasserver',
            name='vpn_connected',
            field=models.BooleanField(default=False, verbose_name='النفق متصل الآن'),
        ),
        migrations.AddField(
            model_name='nasserver',
            name='vpn_last_handshake',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال VPN'),
        ),
        migrations.AddField(
            model_name='nasserver',
            name='vpn_password',
            field=models.CharField(blank=True, max_length=40, verbose_name='باسورد اتصال VPN'),
        ),
        migrations.AddField(
            model_name='nasserver',
            name='vpn_tunnel_port',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='بورت النفق المخصص'),
        ),
        migrations.AddField(
            model_name='nasserver',
            name='vpn_username',
            field=models.CharField(blank=True, max_length=40, verbose_name='يوزر اتصال VPN'),
        ),
    ]
