# Generated by Django 6.1 on 2026-08-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ (جنيه)')),
                ('provider', models.CharField(default='paymob', max_length=20, verbose_name='بوابة الدفع')),
                ('provider_order_id', models.CharField(blank=True, max_length=100, verbose_name='رقم الطلب لدى البوابة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'تم الدفع'), ('failed', 'فشلت')], default='pending', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.company')),
            ],
            options={
                'verbose_name': 'معاملة دفع',
                'verbose_name_plural': 'معاملات الدفع',
                'ordering': ['-created_at'],
            },
        ),
    ]
