# Generated by Django 6.1 on 2026-09-01 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('subscribers', '0002_remove_subscriber_uniq_username_per_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscriber',
            field=models.ForeignKey(blank=True, help_text='لو محدد، معناها دفعة تجديد اشتراك عميل نهائي من بوابة العميل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscribers.subscriber'),
        ),
    ]
