# Generated by Django 6.1 on 2026-08-29 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموزع')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع / المنطقة')),
                ('debt_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأقصى المسموح للدين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resellers', to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'موزّع',
                'verbose_name_plural': 'الموزعون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DebtTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('card_delivery', 'تسليم كروت على الحساب'), ('payment', 'سداد دفعة'), ('manual_adjustment', 'تعديل يدوي')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ (جنيه)')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة السداد')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سُجّلت بواسطة')),
                ('voucher_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.voucherbatch', verbose_name='دفعة الكروت المرتبطة')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='debts.reseller', verbose_name='الموزّع')),
            ],
            options={
                'verbose_name': 'حركة دين',
                'verbose_name_plural': 'حركات الديون',
                'ordering': ['-created_at'],
            },
        ),
    ]
