# Generated by Django 6.1 on 2026-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النقل لسلة المهملات'),
        ),
        migrations.AddField(
            model_name='reseller',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='في سلة المهملات'),
        ),
    ]
