# Generated by Django 6.1 on 2026-08-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadNas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasname', models.CharField(help_text='عنوان IP بتاع الجهاز', max_length=128, unique=True)),
                ('shortname', models.CharField(max_length=32)),
                ('type', models.CharField(default='mikrotik', max_length=30)),
                ('secret', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'RadNas (جهاز NAS)',
                'verbose_name_plural': 'RadNas (أجهزة NAS)',
                'db_table': 'nas',
            },
        ),
        migrations.CreateModel(
            name='RadCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(default='Cleartext-Password', max_length=64)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'verbose_name': 'RadCheck (بيانات دخول RADIUS)',
                'verbose_name_plural': 'RadCheck (بيانات دخول RADIUS)',
                'db_table': 'radcheck',
                'indexes': [models.Index(fields=['username'], name='radcheck_usernam_6d2441_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'verbose_name': 'RadReply (صلاحيات الجلسة)',
                'verbose_name_plural': 'RadReply (صلاحيات الجلسة)',
                'db_table': 'radreply',
                'indexes': [models.Index(fields=['username'], name='radreply_usernam_50e2f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadAcct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acctsessionid', models.CharField(db_index=True, max_length=64)),
                ('acctuniqueid', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('nasipaddress', models.GenericIPAddressField()),
                ('nasportid', models.CharField(blank=True, max_length=32)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('callingstationid', models.CharField(blank=True, max_length=50, verbose_name='MAC العميل')),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctinputoctets', models.BigIntegerField(default=0, verbose_name='بايت مرفوعة')),
                ('acctoutputoctets', models.BigIntegerField(default=0, verbose_name='بايت منزّلة')),
                ('acctterminatecause', models.CharField(blank=True, max_length=32)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.company')),
            ],
            options={
                'verbose_name': 'RadAcct (جلسة استخدام)',
                'verbose_name_plural': 'RadAcct (جلسات الاستخدام)',
                'db_table': 'radacct',
                'indexes': [models.Index(fields=['username'], name='radacct_usernam_4fd6da_idx'), models.Index(fields=['acctstoptime'], name='radacct_acctsto_d45083_idx')],
            },
        ),
    ]
