# Generated by Django 6.1 on 2026-08-29 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الباقة')),
                ('quota_mb', models.PositiveIntegerField(blank=True, help_text='اتركه فارغًا لباقة غير محدودة الكمية', null=True, verbose_name='الكوطة بالميجابايت')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدة الصلاحية (أيام)')),
                ('speed_limit_kbps', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد السرعة (كيلوبت/ث)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر (جنيه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'ordering': ['price'],
            },
        ),
    ]
