# Generated by Django 6.1 on 2026-09-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allow_open_speed',
            field=models.BooleanField(default=False, verbose_name='السماح بالعمل بالسرعة المفتوحة (بدون حد أقصى)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='block_adult_sites',
            field=models.BooleanField(default=False, verbose_name='إيقاف الدخول على المواقع الإباحية'),
        ),
        migrations.AddField(
            model_name='plan',
            name='speed_equation_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل معادلة السرعة (توزيع عادل وقت الزحمة)'),
        ),
    ]
