# Generated by Django 6.1 on 2026-08-29 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='عدد الكروت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_batches', to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='plans.plan', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'دفعة كروت',
                'verbose_name_plural': 'دفعات الكروت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود الكارت')),
                ('status', models.CharField(choices=[('unused', 'غير مستخدم'), ('active', 'مفعّل'), ('expired', 'منتهي الصلاحية')], default='unused', max_length=10, verbose_name='الحالة')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='عنوان الجهاز (MAC)')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='plans.plan', verbose_name='الباقة')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.voucherbatch', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'كارت',
                'verbose_name_plural': 'الكروت',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم القالب')),
                ('primary_color', models.CharField(default='#1BA89B', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#E7A83D', max_length=7, verbose_name='اللون الثانوي')),
                ('logo_text', models.CharField(default='ConnectOS', max_length=40, verbose_name='نص الشعار على الكارت')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الدعم الفني الظاهر على الكارت')),
                ('is_default', models.BooleanField(default=False, verbose_name='القالب الافتراضي')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_templates', to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'قالب كارت',
                'verbose_name_plural': 'قوالب الكروت',
            },
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.vouchertemplate', verbose_name='القالب'),
        ),
    ]
