# Generated by Django 6.1 on 2026-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchertemplate',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='voucher_backgrounds/', verbose_name='صورة خلفية مخصصة (اختياري)'),
        ),
        migrations.AddField(
            model_name='vouchertemplate',
            name='layout_json',
            field=models.TextField(blank=True, help_text='بيتحدد تلقائيًا من مصمم السحب والإفلات — متعدلوش يدوي', verbose_name='مواضع العناصر (JSON)'),
        ),
        migrations.AddField(
            model_name='vouchertemplate',
            name='show_qr',
            field=models.BooleanField(default=True, verbose_name='إظهار QR Code'),
        ),
    ]
