# Generated by Django 6.1 on 2026-09-01 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companysettings_subaccountinvite'),
        ('subscribers', '0003_subscriber_balance_subscriber_deleted_at_and_more'),
        ('vouchers', '0002_vouchertemplate_background_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherbatch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النقل لسلة المهملات'),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='في سلة المهملات'),
        ),
        migrations.CreateModel(
            name='TopupBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='في سلة المهملات')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النقل لسلة المهملات')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة كل كارت (جنيه)')),
                ('quantity', models.PositiveIntegerField(verbose_name='عدد الكروت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_batches', to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'دفعة كروت شحن رصيد',
                'verbose_name_plural': 'دفعات كروت شحن الرصيد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopupCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='كود الكارت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة (جنيه)')),
                ('status', models.CharField(choices=[('unused', 'غير مستخدم'), ('used', 'تم استخدامه')], default='unused', max_length=10, verbose_name='الحالة')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='vouchers.topupbatch', verbose_name='الدفعة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_cards', to='core.company', verbose_name='الشركة')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup_redemptions', to='subscribers.subscriber', verbose_name='استخدمه المشترك')),
            ],
            options={
                'verbose_name': 'كارت شحن رصيد',
                'verbose_name_plural': 'كروت شحن الرصيد',
                'ordering': ['-id'],
            },
        ),
    ]
