# Generated by Django 6.1 on 2026-09-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('max_clients', models.PositiveIntegerField(verbose_name='أقصى عدد مشتركين')),
                ('max_servers', models.PositiveIntegerField(verbose_name='أقصى عدد سيرفرات')),
                ('max_print_cards', models.PositiveIntegerField(verbose_name='أقصى عدد كروت طباعة')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر الشهري (جنيه)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='الأكثر طلبًا')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب في العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة للاشتراك')),
            ],
            options={
                'verbose_name': 'باقة اشتراك المنصة',
                'verbose_name_plural': 'باقات اشتراك المنصة',
                'ordering': ['order', 'price_monthly'],
            },
        ),
        migrations.AddField(
            model_name='platformpayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AddField(
            model_name='platformpayment',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='بيتفعّل يدويًا من مدير المنصة بعد ما يتأكد من وصول المبلغ للمحفظة', verbose_name='تم تأكيد الدفع'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('starter', 'البداية'), ('growth', 'النمو'), ('pro', 'الاحتراف')], default='starter', help_text='حقل قديم قبل باقات PlatformPlan — لسه موجود لتوافق البيانات القديمة', max_length=20, verbose_name='خطة الاشتراك في المنصة (قديم)'),
        ),
        migrations.AddField(
            model_name='company',
            name='platform_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.platformplan', verbose_name='باقة المنصة'),
        ),
    ]
