# Generated by Django 6.1 on 2026-09-01 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_platform_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_suspend_enabled', models.BooleanField(default=True, verbose_name='إيقاف المشتركين المنتهيين تلقائيًا')),
                ('auto_suspend_time', models.TimeField(default='00:00', verbose_name='موعد الإيقاف اليومي')),
                ('auto_delete_expired_enabled', models.BooleanField(default=False, verbose_name='نقل المشتركين المنتهيين لسلة المهملات تلقائيًا')),
                ('auto_delete_grace_days', models.PositiveIntegerField(default=7, verbose_name='بعد كام يوم من الانتهاء')),
                ('single_server_login_enabled', models.BooleanField(default=True, help_text='لو متوقف، هيتقفل المشترك على السيرفر اللي دخل بيه أول مرة بس', verbose_name='السماح للمشترك بالدخول من أي سيرفر')),
                ('auto_search_enabled', models.BooleanField(default=True, verbose_name='تفعيل البحث التلقائي عند الكتابة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركات',
            },
        ),
        migrations.CreateModel(
            name='SubAccountInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='كود الانضمام')),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('support', 'دعم فني')], default='support', max_length=20, verbose_name='الصلاحية الممنوحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='استخدمه')),
            ],
            options={
                'verbose_name': 'كود انضمام حساب فرعي',
                'verbose_name_plural': 'أكواد انضمام الحسابات الفرعية',
                'ordering': ['-created_at'],
            },
        ),
    ]
