# Generated by Django 6.1.1 on 2026-09-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companysettings_subaccountinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='override_max_clients',
            field=models.PositiveIntegerField(blank=True, help_text='سيبها فاضية عشان تستخدم حد الباقة المشترك فيها. لو حطيت رقم هنا، هو اللي هيتطبق بدل حد الباقة.', null=True, verbose_name='حد مخصص لعدد المشتركين'),
        ),
        migrations.AddField(
            model_name='company',
            name='override_max_print_cards',
            field=models.PositiveIntegerField(blank=True, help_text='سيبها فاضية عشان تستخدم حد الباقة المشترك فيها. لو حطيت رقم هنا، هو اللي هيتطبق بدل حد الباقة.', null=True, verbose_name='حد مخصص لعدد كروت الطباعة شهريًا'),
        ),
        migrations.AddField(
            model_name='company',
            name='override_max_servers',
            field=models.PositiveIntegerField(blank=True, help_text='سيبها فاضية عشان تستخدم حد الباقة المشترك فيها. لو حطيت رقم هنا، هو اللي هيتطبق بدل حد الباقة.', null=True, verbose_name='حد مخصص لعدد السيرفرات'),
        ),
        migrations.AddField(
            model_name='company',
            name='unlimited_usage',
            field=models.BooleanField(default=False, help_text='لو مفعّل، الشركة دي مش هتتقيد بأي حد من حدود باقتها (عدد مشتركين/سيرفرات/كروت طباعة شهريًا) مهما كانت باقتها — بيتحكم فيه مدير المنصة بس من شاشة "عملاء المنصة".', verbose_name='بدون أي حدود استخدام'),
        ),
    ]
