# Generated by Django 6.1.1 on 2026-09-05 05:36

from django.db import migrations


def fix_existing_superuser_roles(apps, schema_editor):
    """تصحيح لمرة واحدة: أي حساب سوبريوزر (زي أي حساب اتعمل قبل كده بأمر
    createsuperuser) بيتحول لـ platform_admin تلقائيًا، بنفس منطق
    User.save() الجديد — عشان الحسابات القديمة اللي اتعملت قبل التعديل ده
    تتصلح من غير ما حد يحتاج يدخل /admin/ يعدّلها يدويًا."""
    User = apps.get_model("core", "User")
    User.objects.filter(is_superuser=True).exclude(role="platform_admin").update(role="platform_admin")


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_usage_limit_overrides'),
    ]

    operations = [
        migrations.RunPython(fix_existing_superuser_roles, reverse_noop),
    ]
