# Generated by Django 6.1.1 on 2026-09-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_existing_superuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='بيتحدّث تلقائيًا لحظة التفعيل — بيتحكم في ظهور شريط "تم التفعيل" لفترة قصيرة بعدها.', null=True, verbose_name='تاريخ آخر تفعيل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='لو متوقف، الشركة تقدر تفتح لوحة التحكم وتتصفحها عادي، لكن مايقدروش يستخدموا أي ميزة فعلية (إضافة جهاز/مشترك/كروت...إلخ) لحد ما يتفعّل الحساب.', verbose_name='نشط'),
        ),
    ]
