"""
Django settings for connectos project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================================================
# إعدادات حساسة عن طريق متغيرات البيئة (Environment Variables)
# القيم الافتراضية هنا مخصصة للتطوير المحلي فقط عشان المشروع يفضل يشتغل
# فورًا بدون أي إعداد إضافي. في السيرفر الفعلي (production) لازم تتحدد
# القيم دي كـ environment variables حقيقية ومختلفة، وأهمها DJANGO_DEBUG=False.
# ==========================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-^t#m+21yn%d$jmhios7g!(ci$2u*kf1_evosd@sfgkk+zax-r6",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")

# إعدادات أمان إضافية تُفعّل تلقائيًا لما DEBUG=False (يعني في بيئة إنتاج فعلية)
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "True") == "True"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_SECURE_HSTS_PRELOAD", "False") == "True"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'nas_manager',
    'plans',
    'vouchers',
    'debts',
    'dashboard',
    'radius_core',
    'subscribers',
    'notifications',
    'payments',
    'portal',
]

AUTH_USER_MODEL = 'core.User'
LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'core:login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CompanyActivationMiddleware',
]

# ==========================================================================
# حجب المحتوى الإباحي — إعداد أساسي إجباري على مستوى المنصة كلها، وليس
# اختيارًا لكل باقة أو كل شركة. بيتفرض على كل جهاز ميكروتيك تلقائيًا من
# سكريبت التركيب نفسه (nas_manager.content_filter)، ومفيش أي مكان في
# الداشبورد بيقدر يوقفه. المتغير ده بيحدد مصدر قائمة النطاقات المحجوبة
# (يقدر مدير المنصة بس، من على السيرفر مباشرة، يغيّره لقائمة تانية لو
# احتاج — لكن الميزة نفسها (وجود فلتر إجباري) مش قابلة للإلغاء من الكود).
CONTENT_FILTER_ADLIST_URL = os.environ.get(
    "CONTENT_FILTER_ADLIST_URL",
    "https://raw.githubusercontent.com/blocklistproject/Lists/master/porn.txt",
)

ROOT_URLCONF = 'connectos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.company_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'connectos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# ملاحظة مهمة: SQLite ممتاز للتطوير والتجربة، لكن جداول radius_core
# (radcheck/radreply/radacct/nas) مصممة لتُقرأ مباشرة من FreeRADIUS عن طريق
# rlm_sql. في الإنتاج الفعلي لازم PostgreSQL أو MySQL (نفس القاعدة اللي
# هيتحدد فيها FreeRADIUS SQL module)، تقدر تفعّلها بمجرد ضبط DATABASE_URL
# أو المتغيرات تحت في بيئة السيرفر الحقيقي.

if os.environ.get("DB_ENGINE") == "postgresql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get("DB_NAME", "connectos"),
            'USER': os.environ.get("DB_USER", "connectos"),
            'PASSWORD': os.environ.get("DB_PASSWORD", ""),
            'HOST': os.environ.get("DB_HOST", "localhost"),
            'PORT': os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

if not DEBUG:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ==========================================================================
# البريد الإلكتروني (لازم لصفحة "نسيت كلمة المرور"). بيطبع الإيميلات في
# الـ Console افتراضيًا وقت التطوير، وبيبعت SMTP حقيقي لو ضبطت المتغيرات دي.
# (Django 6 بيستخدم إعداد MAILERS الجديد بدل EMAIL_BACKEND القديم المباشر)
# ==========================================================================
if os.environ.get("EMAIL_HOST"):
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'HOST': os.environ.get("EMAIL_HOST"),
            'PORT': int(os.environ.get("EMAIL_PORT", "587")),
            'USERNAME': os.environ.get("EMAIL_HOST_USER", ""),
            'PASSWORD': os.environ.get("EMAIL_HOST_PASSWORD", ""),
            'USE_TLS': os.environ.get("EMAIL_USE_TLS", "True") == "True",
        },
    }
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "ConnectOS <no-reply@connectos.example.com>")


# ==========================================================================
# تكاملات خارجية — بوابة الدفع Paymob وبوت تيليجرام للتنبيهات
# القيم دي فاضية بشكل افتراضي، والنظام بيشتغل عادي من غيرها لكن مع تعطيل
# الميزات المرتبطة بيها (وده موضّح للمستخدم في واجهة الإعدادات).
# ==========================================================================

PAYMOB_API_KEY = os.environ.get("PAYMOB_API_KEY", "")
PAYMOB_INTEGRATION_ID = os.environ.get("PAYMOB_INTEGRATION_ID", "")
PAYMOB_HMAC_SECRET = os.environ.get("PAYMOB_HMAC_SECRET", "")
PAYMOB_IFRAME_ID = os.environ.get("PAYMOB_IFRAME_ID", "")

# منفذ RouterOS API الافتراضي لأجهزة الميكروتيك
MIKROTIK_API_DEFAULT_PORT = int(os.environ.get("MIKROTIK_API_DEFAULT_PORT", "8728"))
MIKROTIK_API_TIMEOUT = int(os.environ.get("MIKROTIK_API_TIMEOUT", "4"))

# عنوان سيرفر RADIUS المركزي بتاع المنصة — بيتحط في سكريبت التركيب اللي
# بيتلزق على جهاز الميكروتيك (نفس فكرة "من هنا" في Smart Radius)
RADIUS_SERVER_HOST = os.environ.get("RADIUS_SERVER_HOST", "radius.connectos.example.com")
VPN_PUBLIC_HOST = os.environ.get("VPN_PUBLIC_HOST", "vpn.connectos.example.com")
RADIUS_ACCOUNTING_WEBHOOK = os.environ.get(
    "RADIUS_ACCOUNTING_WEBHOOK", "https://api.connectos.example.com/radius/accounting/"
)
